sudo: false
language: python
env:
    - CONDA="python=2.7"
    - CONDA="python=3.3"
    - CONDA="python=3.4"
    - CONDA="python=3.5"
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes
    - conda update conda
    - conda info -a
    - conda install numpy scipy matplotlib nose coverage networkx
    - pip install nibabel
    - travis_retry pip install coveralls
install:
    - python setup.py install
script:
    - nosetests -v --with-coverage --cover-package=nitime
after_success:
    - coveralls
